### ISSUE TITLE
Using it with has_many through and polymorphic relationships

### ISSUE THREAD

**Issue by chadwilken** [exAspArk/batch-loader#11]
I am just getting started with the gem and have a few questions:
 - Is there a way to make it work with a polymorphic relationship where there is both an id and a type column?
 - Is it possible to have this work with has_many through relationships? I'm not sure what I would use in the `for` call to `BatchLoader` or if that is not it's intended purpose. We have a lot of join tables and support for this model would be crucial.

Looks promising and like a great gem!

**Comment by exAspArk** [comment]
Hi @chadwilken!

> * Is there a way to make it work with a polymorphic relationship where there is both an id and a type column?

Currently, you'd probably need to do something like:

```ruby
BatchLoader.for({id: 1, type: Author}).batch do |keys, loader|
  keys.group_by { |k| k[:type] }.each do |type, keys|
    records = type.where(id: keys.map { |k| k[:id] })
    records.each { |r| loader.call({id: r.id, type: type}, r) }
  end
end
```

It's so verbose because a single `BatchLoader` block can't differentiate between types automatically. However, if https://github.com/exAspArk/batch-loader/pull/6 will be merged, it'll allow doing something like:

```ruby
BatchLoader.for(1).batch(key: Author) do |keys, loader, batch_args|
  records = batch_args[:key].where(id: keys)
  records.each { |r| loader.call(r.id, r) }
end
```

> * Is it possible to have this work with has_many through relationships? I'm not sure what I would use in the for call to BatchLoader or if that is not it's intended purpose. We have a lot of join tables and support for this model would be crucial.

Interesting question 🤔  For example, If we take a look at these models from the [Rails Guide](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association):

```ruby
class Physician < ApplicationRecord 
  has_many :appointments
  has_many :patients, through: :appointments
end

class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

class Patient < ApplicationRecord  
  has_many :appointments  
  has_many :physicians, through: :appointments
end
```

You can try to do something like:

```ruby
physician = Physician.take

patients = BatchLoader.for(physician.id).batch(default_value: []) do |physician_ids, loader|
  appointments = Appointment.where(physician_id: physician_ids).includes(:patient)
  appointments.each { |a| loader.call(a.physician_id) { |memo| memo << a.patient } }
end
```

**Comment by chadwilken** [comment]
I thought about passing a hash, but wasn't sure if it would work as intended, but I'll give that a go. I will also try the has_many through example you wrote. I was wondering if that is how I was going to have to do it, but wasn't sure if it would cause a N+1 on the join model, but since it is lazy loaded as well it makes sense now that it would just load them all and use the includes to eager load the patient model.

Thanks for the response.

**Comment by exAspArk** [comment]
P.S. We added a support for passing a `key` argument in the `1.2.0` version (https://github.com/exAspArk/batch-loader/pull/12):

```ruby
BatchLoader.for(1).batch(key: Author) do |ids, loader, args|
  records = args[:key].where(id: ids)
  records.each { |r| loader.call(r.id, r) }
end
```
