### ISSUE TITLE
Queue for batching for `ActiveRecord::Relation` batching

### ISSUE THREAD

**Issue by ZJvandeWeg** [exAspArk/batch-loader#13]
We're using this gem for preloading related data on ActiveRecord models from another data store. This works well, but I wonder if the interface for AR could be improved.

Consider the following example:

```ruby
# Pipeline is a collection of CI jobs, for example an rspec and rubocop job can be in that 
pipelines = Pipeline.last(10)
pipelines.each { |p| p.lazy_commit } # list the commit for batching

# What I would want to write:
pipelines = Pipeline.last(10).with_batched(:lazy_commit)
```
This way I can forget about when the pipelines are actually fetched from the database. I understand this is a minor issue, and having a hook like that might make more sense to provide in `rails/rails` than in this code base. What do you think?

**Comment by exAspArk** [comment]
Yeah, that's a good question!

I think there are a few options to consider:

* `BatchLoader` monkey-patches AR, Mongoid, etc. or/and Ruby arrays to add the methods for preloading and batching

It's the least preferable option for me personally.

* Don't implement the feature :)

So, for example, DIY with the onliners like:

```ruby
pipelines = Pipeline.last(10).each(&:lazy_commit)
```

* Implement it in a separate module or gem

For example, @mathieul recently shared the [Batch Loader - Active Record](https://github.com/mathieul/batch-loader-active-record) gem he created to integrate `BatchLoader` with `ActiveRecord`.

**Comment by exAspArk** [comment]
Closed the issue for now. Feel free to add your thoughts :)
