### ISSUE TITLE
Loading multiple items, they get attached to the wrong parent (GraphQL)

### ISSUE THREAD

**Issue by alxx** [exAspArk/batch-loader#17]
It's quite possible that I'm doing something wrong, because I don't understand 100% how this gem works, but I would appreciate any help.

I'm trying to implement the 1:Many solution (`Post has_many Comments`) in GraphQL and here's my `Post` query field for its comments:

```ruby
  field :comments, types[Types::CommentType] do
    #resolve ->(o, _, _) { o.comments }

    resolve ->(o, _, _) do
      BatchLoader.for(o.id).batch(default_value: []) do |ids, loader|
        Comment.where(post_id: ids).each do |c|
          loader.call(o.id) { |memo| memo << c }
        end
      end
    end
  end
```

Now in my database I have a `Comment` attached to the `Post` with the id: 139. While that comment does appear in the query result, which is successfully lazy, the comment appears attached to the very first `Post` listed, which has another id. And its actual parent (`Post` with id 139) shows no comments in the query results.

What am I doing wrong?

**Comment by alxx** [comment]
Duplicate of #16.

**Comment by exAspArk** [comment]
Yeah, thanks for opening the issue. I assume that the problem is that only single object (`o`) from outside the `BatchLoader` is bound to the block. I updated the README example.
