### ISSUE TITLE
Question: how to handle through association

### ISSUE THREAD

**Issue by cabello** [exAspArk/batch-loader#18]
Hi, thanks for the gem ❤️ 

I am trying to wrap my head around the concept and I have the following model, where one client has many transfers **through** accounts.

```ruby
class Client
  has_many :accounts
  has_many :transfers, through: :accounts
end
```

Imagine `ClientType` has a field called `transfers`, this is my attempt to lazy load it (because it sounds very similar to 1-many example):

```ruby
ClientType = GraphQL::ObjectType.define do
  ...
  field :transfers, types[TransferType] do
    resolve ->(client, args, ctx) do
      BatchLoader.for(client.id).batch(default_value: []) do |client_ids, loader|
        Transfer.includes(:client).joins(:client).where(clients: { id: client_ids }).each do |transfer|
          loader.call(transfer.client.id) { |memo| memo << transfer }
        end
      end
    end
end
```

However this is resulting in multiple queries to the Transfer table, exactly like a N+1 (one per client id).

Any idea what am I missing? Before that I was using `Client.includes(:transfers)` and it was working as expected resulting in queries like:

```
D, [2018-01-30T21:37:54.025760 #19309] DEBUG -- :   Client Load (0.8ms)  SELECT "clients".* FROM "clients" WHERE "clients"."deleted_at" IS NULL AND "clients"."canonical_id" IN ('user-15', 'user-16', 'user-17', 'user-18', 'user-19', 'user-20', 'user-21', 'user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13')
D, [2018-01-30T21:37:54.092492 #19309] DEBUG -- :   Account Load (0.7ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."deleted_at" IS NULL AND "accounts"."client_id" IN (31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50)
D, [2018-01-30T21:37:54.117644 #19309] DEBUG -- :   Transfer Load (1.7ms)  SELECT "transfers".* FROM "transfers" WHERE "transfers"."deleted_at" IS NULL AND "transfers"."account_id" IN (16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 32, 33, 34)
```

I feel like I am almost there, maybe I need an `Account` query first and a `Transfer` account right after that.

**Comment by exAspArk** [comment]
Hey, @cabello!

Thanks for opening this issue!

Could you please confirm that `client_ids` array contains multiple elements? For example, with `puts client_ids`, logger, pry, etc.? Did you add [use BatchLoader::GraphQL](https://github.com/exAspArk/batch-loader#graphql-example) line to your schema?

If it contains multiple elements like `['user-15', 'user-16', ...]`, then probably the issue with the ORM which you're using. For example, maybe the `joins(:client)` is not necessary because there are no joins in your previous logs.

**Comment by cabello** [comment]
Hm... I tried again today using the same example code and it worked like a charm. Maybe I was missing the `use BatchLoader::GraphQL` in my schema!? 🤔. I could swear I had added it.

Thanks for getting back to me and it was nice to meet you at the GraphQL meet up, looking forward for more interactions! 🤗

**Comment by exAspArk** [comment]
@cabello glad it works for you!

It was nice to meet you, too! Looking forward to seeing you as a speaker at the meetup and learning from you one day 😃
