### ISSUE TITLE
Error with has_many relationship.

### ISSUE THREAD

**Issue by rlb3** [exAspArk/batch-loader#19]
I have a delivery object have has_many workflows.

I have this as my workflows field in my delivery type:

```ruby
field :workflows, types[Types::WorkflowType] do
    description "All workflows for a delivery"
    resolve ->(obj, args, ctx) {
      BatchLoader.for(obj.id).batch do |delivery_ids, loader|
        Workflow.where(delivery_id: delivery_ids).each { |workflow| loader.call(workflow.delivery_id, workflow) }
      end
    }
  end
```

I'm getting this error when run a query:

```ruby
NoMethodError (undefined method `each' for #<Workflow:0x007fcccdcd5978>):
  app/controllers/graphql_controller.rb:12:in `execute'
```

I'm not sure where this error is coming from.

**Comment by rlb3** [comment]
I think I made one mistake with `loader.call(workflow.delivery_id, workflow)`. I change it to `loader.call(workflow.id, workflow)` I no longer get the error but workflow is nil.

**Comment by cabello** [comment]
For a `has_many` relationship you want a list of items to be returned when lazy loading your records, for example:

```ruby
field :state_histories, types[TransferStateHistoryType] do
  resolve ->(transfer, _, _) do
    BatchLoader.for(transfer.id).batch(default_value: []) do |transfer_ids, loader|
      TransferStateHistory.where(transfer_id: transfer_ids).each do |state_history|
        loader.call(state_history.transfer_id) { |memo| memo << state_history }
      end
    end
  end
end
```

In your case:
- The `delivery_id` is how the items are grouped.
- The `Workflow` is a item in the list that will be returned.

**Comment by rlb3** [comment]
Thank you. That worked for me.
