### ISSUE TITLE
Batch Load in GraphQL without a field attached to it.

### ISSUE THREAD

**Issue by DamirSvrtan** [exAspArk/batch-loader#23]
Hi 👋Thank you for all of your work on this gem!

I've got a question in the context of GraphQL. Let's take a typical example, a Post has an author.

You could have a Post and a User Type, and load the author (user) in a resolver. Example:

```ruby
class Types::ProjectType < Types::BaseObject
  field :id, ID, null: true
  field :name, String, null: true
  field :author, resolver: Resolvers::Author
end
```

```ruby
module Resolvers
  class Author < Resolvers::Base
    type Types::UserType, null: true

    def resolve
      BatchLoader.for(object.author_id]).batch do |user_ids, loader|
        User.where(id: user_ids).each do |user|
          loader.call(user.id, user)
        end
      end
    end
  end
end
```

The example above works great and the N+1 HTTP/SQL problem does not exist 💯 

Due to some reasons, I'd like to load the `author_name` inside of the Post type and not expose the Author type at all.

I've tried loading the data in following manner, however unfortunately the N+1 problem starts occurring:

```ruby
class Types::ProjectType < Types::BaseObject
  field :id, ID, null: true
  field :author_name, String, null: true

  def author_name
     author.name
  end
  
  private

  def author
      BatchLoader.for(object.author_id]).batch do |user_ids, loader|
        User.where(id: user_ids).each do |user|
          loader.call(user.id, user)
        end
      end
  end
end
```

I'm guessing this is due to the fact that the later implementation does not load the other author records (just because Ruby method calls work that way) so it starts loading them one by one.

Do you have a suggestion on how to tackle an implementation like this? Thank you!

**Comment by exAspArk** [comment]
Hey @DamirSvrtan!

Yeah, to make BatchLoader + GraphQL work lazily to avoid N+1 queries it's required to return a `BatchLoader` instance as the result.

```ruby
class Types::ProjectType < Types::BaseObject
  field :id, ID, null: true
  field :author_name, String, null: true

  def author_name
    lazy_author_name
  end
  
  private

  def lazy_author_name
    BatchLoader.for(object.author_id).batch do |user_ids, loader|
      User.where(id: user_ids).each do |user|
        loader.call(user.id, user.name)
      end
    end
  end
end
```

GraphQL-Ruby gem currently uses classes as a signature to identify lazy objects, collect them and then resolve at once. Does that work for you? 

Just curious, do you GraphQL + BatchLoader at Netflix? I thought you guys are using Falcor :)

**Comment by DamirSvrtan** [comment]
Hey @exAspArk, thanks for promptly answering! That's interesting that it needs back a batch loader instance back, how do you solve then when in a given case you need to load two different attributes from the same resource? I'm talking about the scenario such where you'd need an authors email in addition to the authors name?

Would you write two batch loaders,(would need to add a `lazy_author_email` method) and then count on the batch loaders cache mechanism to kick in so that it does not perform the same query twice? Or is there a smarter way to tackle it?

**Comment by exAspArk** [comment]
Hey @DamirSvrtan!

Because GraphQL Ruby gem requires to return a lazy instance, you could potentially nest `BatchLoaders`:

```ruby
class Types::ProjectType < Types::BaseObject
  field :id, ID, null: true
  field :author_name, String, null: true
  field :author_email, String, null: true

  def author_name
    BatchLoader.for(object).batch do |projects, loader|
      projects.each { |p| loader.call(p, lazy_author.name) }
    end
  end

  def author_email
    BatchLoader.for(object).batch do |projects, loader|
      projects.each { |p| loader.call(p, lazy_author.email) }
    end
  end
  
  private

  def lazy_author
    BatchLoader.for(object.author_id).batch do |user_ids, loader|
      User.where(id: user_ids).each do |user|
        loader.call(user.id, user)
      end
    end
  end
end
```

For a query like:

```gql
{
  projects {
    id
    author_name  # <= GraphQL lazily will collect all batch loaders for "author_name"
    author_email # <= GraphQL lazily will collect all batch loaders for "author_email"
                 # then it'll resolve the fields ^ by resolving all "lazy_author" and will do that once
  }
}
```

It should execute the `User.where(id: user_ids)` DB query only once.

**Comment by DamirSvrtan** [comment]
Hi @exAspArk 👋Sorry for not closing this earlier. At the end I did not solve it by nesting batch loaders (not sure if that would work).

What I did is make proc objects lazy in graphql:

```ruby
class TheSchema < GraphQL::Schema
  lazy_resolve(Proc, :call)
end
```

```ruby
class Types::ProjectType < Types::BaseObject
  field :id, ID, null: true
  field :author_name, String, null: true
  field :author_age, String, null: true

  def author_name
    author && -> { author.name }
  end

  def author_age
    author && -> { author.age }
  end
  
  private

  def author
      BatchLoader.for(object.author_id).batch do |user_ids, loader|
        User.where(id: user_ids).each do |user|
          loader.call(user.id, user)
        end
      end
  end
end
```
