### ISSUE TITLE
undefined method to_ary on ActiveRecord objects

### ISSUE THREAD

**Issue by caleb** [exAspArk/batch-loader#31]
Hi,

I'm using `BatchLoader` for queries on my `ActiveRecord` objects and I'm getting an error when I call `Kernel.Array` with the `BatchLoader` proxy:

(This is in a new blank Rails 5.2.2 project with just one model that I haven't done anything to, just to make sure something in my real project wasn't causing the problem)

```ruby
irb(main):002:0> u = User.first
=> #<User id: 1, ...>

irb(main):003:0> b = BatchLoader.for(1).batch {|ids, loader| loader.call(1, u)}
=> #<BatchLoader:0x94261337109840>

irb(main):004:0> Array(b)
Traceback (most recent call last):
        2: from (irb):10
        1: from (irb):10:in `Array'
NoMethodError (undefined method `to_ary' for #<User:0x000055baed851f08>)
Did you mean?  to_key
```

This isn't an issue when calling `Kernel.Array` on the `ActiveRecord` objects directly or the result of `__sync` on the proxy:

```ruby
irb(main):005:0> Array(u)
=> [#<User id: 1,  ...>]

irb(main):006:0> Array(b.__sync)
=> [#<User id: 1,  ...>]
```

`Kernel.Array` is a C function that calls `to_ary` if the object has that method, otherwise it wraps the object in an Array.

What's strange is that my `User` class doesn't have a `to_ary` method  (and neither does `ActiveRecord::Base`), so I don't know why `Kernel.Array` is trying to call it. It must be the way in which `Kernel.Array` detects whether an object responds to a method is different than just calling `respond_to?`, which `BatchLoader` does handle:

```ruby
irb(main):013:0> b = BatchLoader.for(1).batch {|ids, l| l.call(1, u)}
=> #<BatchLoader:0x93972309044200>
irb(main):014:0> b.respond_to?(:to_ary)
=> false
```

Maybe the low level C ruby functions do something different that isn't handled by the proxy correctly?

Also, this seems to affect `ActiveRecord` objects wrapped in the proxy, but not other types of objects I've tested (`Object`, `String`, `Rails`, `Array`), for example:

```ruby
>> b = BatchLoader.for(1).batch {|ids, l| l.call(1, "Hello World")}
=> #<BatchLoader:0x140413397447560>
>> Array(b)
=> ["Hello World"]
```

Any ideas?

--Caleb

**Comment by exAspArk** [comment]
Hi @caleb,

Wow, that is very weird! I found some other examples of weird issues and behaviours around `to_ary`. For example, [TIL: It's OK to return nil from to_ary](https://tenderlovemaking.com/2011/06/28/til-its-ok-to-return-nil-from-to_ary.html) by @tenderlove:

> Ruby will call to_ary, and if method_missing is implemented, it will call method_missing regardless of how your respond_to? returns. The reason ruby will call method_missing is because it could implement to_ary. (As for why it ignores the return value of respond_to?, I don't know)

```ruby
> u = User.last

> u.respond_to?(:to_ary)
=> false

> u.to_ary
NoMethodError: private method `to_ary' called for #<User:0x00007fc655dc9998>
Did you mean?  to_key
	from (irb):2

> u.send(:to_ary)
=> nil
```

🙈

**Comment by exAspArk** [comment]
I think the issue is that `ActiveRecord` (unlike other classes like `Object`, `String`) implements `to_ary` private method in `ActiveRecord::Core`. Then `Array(model)` tries for some reason to call `method_missing(:to_ary)` instead of `send(:to_ary)`, although `respond_to?(:to_ary)` returns `false`:

```ruby
> User.last.method_missing(:to_ary)
NoMethodError: undefined method `to_ary' for #<User:0x00007fa608bf7218>
Did you mean?  to_key
```

Not sure how to fix it for now. But as a temporary solution it is possible to use [Array.wrap](https://api.rubyonrails.org/classes/Array.html#method-c-wrap) from `ActiveSupport` which addresses some of the `Kernel#Array` issues:

> This method is similar in purpose to Kernel#Array, but there are some differences:
>
> If the argument responds to to_ary the method is invoked. Kernel#Array moves on to try to_a if the returned value is nil, but Array.wrap returns an array with the argument as its single element right away.
> 
> If the returned value from to_ary is neither nil nor an Array object, Kernel#Array raises an exception, while Array.wrap does not, it just returns the value.
> 
> It does not call to_a on the argument, if the argument does not respond to to_ary it returns an array with the argument as its single element.

**Comment by stellard** [comment]
Hi,

I am seeing this issue now when calling `flatten` on an array of `BatchLoader` 

```
irb(main):008:0> u = User.first
=> #<User id: ....>
irb(main):009:0> b = BatchLoader.for(1).batch {|ids, loader| loader.call(1, u)}
=> #<BatchLoader:....>
irb(main):010:0> [[b]].flatten
NoMethodError: undefined method `to_ary' for #<User:0x007fb5d8c93890>
```

I have gotten around it by defining `to_ary` for now to return nil. Any ideas?

**Comment by Aristat** [comment]
```
u = User.first
b = BatchLoader.for(1).batch(default_value: []) {|ids, loader| loader.call(1) { |memo| memo << u} }
Array(b)
```

**Comment by dush** [comment]
Adding `public :to_ary` into AppliactionRecord fixed it for me.
