### ISSUE TITLE
"Prime" items

### ISSUE THREAD

**Issue by maletor** [exAspArk/batch-loader#35]
Is there a function to [prime](https://github.com/facebook/dataloader#loading-by-alternative-keys) items into other batches?

The facebook dataloader exposes this function and essentially it affords items loaded to be found by another key. This is especially useful, for instance, so that when you are batch load Posts for a User you could also prime a Category batch find where a Comment belongs to a Category by a foreign key.

**Comment by exAspArk** [comment]
Hi @maletor,

Thank you for sharing the idea! I imagine the following scenario where it can be useful:

```rb
class Post
  belongs_to :user
end

class User
  belongs_to :avatar
end

class Avatar
end

def lazy_avatar(user)
  BatchLoader.for(user.id).batch do |user_ids, loader|
    Avatar.where(user_id: user_ids).each do |avatar|
      loader.call(avatar.user_id, avatar)
    end
  end
end

def lazy_user(post)
  BatchLoader.for(post.user_id).batch do |user_ids, loader|
    User.where(id: user_ids).each do |user|
    # ^ we could use User.where(...).includes(:avatar) to prime in this batch
      loader.call(user.id, user)
    end
  end
end
```

Implementing the "prime" is possible. But the main challenge is to design a good API for developers. BatchLoader doesn't require developers to define and share the "loaders" (dataloader) or separate classes, everything lives in the block. It simplifies the usage but doesn't allow to share one BatchLoader reference in another.
