### ISSUE TITLE
Many to many relationship

### ISSUE THREAD

**Issue by Derenge** [exAspArk/batch-loader#38]
Thanks for an awesome gem! I love the flexibility and the clarity you've achieved by reducing the "magic" involved.

I think I may be missing a key understanding since I can't figure out how I would represent a many to many relationship.

The documentation talks about the memoization being extremely useful for 1:many relationships, and I believe this is because `loader.call(1, value)` overwrites the value for `1`. I think I'm missing how multiple `BatchLoader.for(1)` calls get grouped together.

The test situation I am working with follows

```ruby
# ActiveRecord classes
class Parent < ActiveRecord::Base
  has_and_belongs_to_many :children
end

class Child < ActiveRecord::Base
  has_and_belongs_to_many :parents
end

# Usage
BatchLoader::GraphQL.for(parent.id).batch(default_value: []) do |parent_ids, loader|
  children_for_parent_ids(parent_ids).each do |loaded_child|
    loader.call([unsure]) { |memo| memo << loaded_child}
  end
end

# How I think I could make it work...
BatchLoader::GraphQL.for(parent.id).batch(default_value: []) do |parent_ids, loader|
  children_for_parent_ids(parent_ids).each do |loaded_child|
    parent_ids_for_child(loaded_child).each do |parent_id|
      loader.call(parent_id) { |memo| memo << loaded_child }
    end
  end
end
```

If this isn't the right place to ask question, feel free to close the issue! I would really appreciate any direction though 😄

**Comment by exAspArk** [comment]
Hi @Derenge,

Thank you for opening this very well described issue! 😍 

For example:

```rb
BatchLoader::GraphQL.for(parent.id).batch(default_value: []) do |parent_ids, loader|
  parents_for_parent_ids(parent_ids).each do |parent|
    loader.call(parent.id) { |memo| memo.concat(parent.children) }
  end
end

def parents_for_parent_ids(parent_ids)
  Parent.includes(:children).where(id: parent_ids) # potentially 1 sql with joins
end
```

Or

```rb
BatchLoader::GraphQL.for(parent.id).batch(default_value: []) do |parent_ids, loader|
  children_by_parent_id(parent_ids).each do |parent_id, children|
    loader.call(parent_id) { |memo| memo.concat(children) }
  end
end

def children_by_parent_id(parent_ids)
  result = Hash.new { |h, k| h[k] = [] }
  Children.includes(:parents).each do |child| # potentially 1 sql with joins
    child.parents.each { |parent| result[parent.id] << child }
  end
  result # can use .each_with_object(...) instead of .each + result variable
end
```

**Comment by Derenge** [comment]
Thanks @exAspArk, it works for a charm!

Out of curiosity have you tried tackling this issue on a generic level? I currently have a working prototype that handles batch loading for ActiveRecord associations based on their macro (`:has_one`, `:belongs_to`, `:has_many`, `:has_and_belongs_to_many`). I've handled the easy cases, and I have a sub-optimal solution for handling the `through:` option for `has_many` and `has_one`. I have yet to tackle the polymorphic option.

I think I might update my solution to try and determine the batch id based off of which record occurs more. For instance, if there are many more parents than children it makes sense to batch on the children ids over the parent ids.

**Comment by exAspArk** [comment]
I think that creating a generic solution for ActiveRecord by using BatchLoader is a good idea.

For example, some tools in such languages as Elixir have nice tools to batch DB requests for associations in GraphQL (absinthe) with just 1 line of code. Another good example is https://github.com/Bajena/ams_lazy_relationships by @Bajena which uses BatchLoader for associations in ActiveModel Serializers.

I'm not planning to build a solution for ActiveRecord in BatchLoader itself. But feel free to create a separate gem if you want :) Closing this issue.
