### ISSUE TITLE
Returning a single result for a 1:Many relationship

### ISSUE THREAD

**Issue by ro-savage** [exAspArk/batch-loader#39]
Great library, this really helped bring our GraphQL response times down!

One thing we are trying to do is have a SQL query with a 1:Many relationship, that we then narrow down to a single result. This is because we can not write a sql query to obtain the result we want as it requires additional logic.

We solved this in our model with
```# Person Model
def contract
  contracts.order(:start_date).where("end_date >= current_date OR end_date is NULL").first
end
```

Where because we have ordered the results, we know the first result is correct.
Alternatively we could return the array, and then pragmatically check  for the result we want by comparing the data returned.

We haven't however been able to solve this with batch-loader in our GraphQL query.
**Attempt 1**
```
BatchLoader::GraphQL.for(obj.id).batch(cache: false) do | person_ids, loader |
  Contract.where(person_id: person_ids)
    .where("contracts.end_date >= current_date OR contracts.end_date is NULL")
    .order(:start_date)
    .each { |contract|
      loader.call(contract.id, contract)
    }
end
```
The BatchLoader doesn't seem to respect the order it receives the model at all.
If return to contracts with `person_id = 1` it doesn't matter what we pass `loader` first or second. It will always return the lowest `contract.id`. (Why is this? How does it choose what to return when it has multiple results for the same id?)

**Attempt 2**
```
contracts = BatchLoader::GraphQL.for(obj.id).batch(default_value: []) do |person_ids, loader|
  Contract.where(person_id: person_ids).where("end_date >= current_date OR end_date is NULL").order(:start_date).each do |contract|
    loader.call(contract.person_id) { |arr| arr << contract }
  end
end

return contracts.first
```
Gives the correct result but now its executes as n+1 again.

**Attempt 3**
```
BatchLoader::GraphQL.for(obj.id).batch(default_value: []) do |person_ids, loader|
  Contract.where(person_id: person_ids).where("end_date >= current_date OR end_date is NULL").order(:start_date).each do |contract|
    loader.call(contract.person_id) { |arr|
      if arr.empty?
        arr << contract
      end
      arr
    }
  end
end
```
This works, except that it returns an array with a single value. Really we just want to return the value.

I am not sure how we can go about this?

Is there a way that we can have the result of an array returned than then manipulate it?
Or is there a way we can ensure the the first/last value is returned when there are conflicting results?
Am I missing something completely?

(Feel free to close. Since this isn't actually a bug or feature. But more not understand usage of the library)

**Comment by exAspArk** [comment]
Hey @ro-savage!

> It will always return the lowest contract.id. (Why is this? How does it choose what to return when it has multiple results for the same id?)

If you're about `person_ids`, then `BatchLoader` implicitly keeps the order (FIFO).

https://github.com/exAspArk/batch-loader/blob/43e4f62ab5e788e635aeca0a4a01def3f7ee5ca6/lib/batch_loader/executor_proxy.rb#L16-L18

However, I'm not sure in which order the `graphql` gem executes the lazy resolvers.

---

> Attempt 1
> loader.call(contract.id, contract)

Shouldn't it be `loader.call(contract.person_id, contract)`?

---

I'm not entirily understand your example. But if you use SQL, you probably might try to `GROUP BY` (per person and then sort) or `JOIN` (persons with joined sorted contracts with limit 1).
