### ISSUE TITLE
batchloader || result

### ISSUE THREAD

**Issue by terencechow** [exAspArk/batch-loader#40]
With the below code, if `some_call` returns `nil`, `get_stuff` returns `nil`. This is because `some_call` returns a `BatchLoader` which never executes and `some_other_call` doesn't get called.

```
def get_stuff
  some_call || some_other_call
end

def some_call
  BatchLoader.for(id) ...
end
```

This occured in my active record models when called directly, thus failing the tests for the method `get_stuff`. However in the controller, which uses a jbuilder that calls `get_stuff`, it is lazily loaded and then when evaluated, it calls `some_other_call` and works properly.

What's the best way to handle this?

**Comment by FX-HAO** [comment]
@terencechow may I know how did you fix it?
