### ISSUE TITLE
Update docs for latest graphql

### ISSUE THREAD

**Issue by davidw** [exAspArk/batch-loader#48]
Looks like schemas are defined differently now, in the ruby-graphql gem:

```
class FooSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

As opposed to the docs for batch-loader which have:

```
Schema = GraphQL::Schema.define do
  query QueryType
  use BatchLoader::GraphQL
end
```

Or am I missing something?
Thanks!

**Comment by exAspArk** [comment]
Hey @davidw,

Thank you for opening the issue! Right, these are two different ways of defining a schema: `.define`-style vs [class-based](https://graphql-ruby.org/schema/class_based_api.html) definition, which was introduced in the 1.8 GraphQL-Ruby version.

Feel free to open a PR and update the examples in the README if you want. The BatchLoader tests cover both of these cases depending on the GraphQL-Ruby version:

https://github.com/exAspArk/batch-loader/blob/879cb72d585af4e7d70f59f606a1995b38fda945/spec/fixtures/graphql_schema.rb#L28-L31

https://github.com/exAspArk/batch-loader/blob/879cb72d585af4e7d70f59f606a1995b38fda945/spec/fixtures/graphql_schema.rb#L62-L65

**Comment by davidw** [comment]
For me the important thing wasn't so much in figuring out how to actually do that, as the doubt that perhaps this project was maybe not that up to date.

**Comment by davidw** [comment]
Not stale :-)

**Comment by davidw** [comment]
Still interested.
