### ISSUE TITLE
Consider new name or alias for 'call'

### ISSUE THREAD

**Issue by davidw** [exAspArk/batch-loader#50]
This is a small, stylistic issue, but it might be clearer to new users if the methods referencing the id's were more explicit.  Something like this, maybe?

```
   BatchLoader::GraphQL.for_id(post.user_id).batch do |user_ids, loader|
      User.where(id: user_ids).each { |user| loader.match_id(user.id, user) }
    end
```

Just a thought.  `call` is pretty generic and doesn't convey as much meaning as a name that says "ok, when given this ID, reference this object".

**Comment by exAspArk** [comment]
Thank you for opening the issue! 

> `call` is pretty generic 

Yes, I agree. On the other hand, `match_id` is too specific and assumes that the first argument is some kind of ID, which not always the case.

In general, `loader` is just a "function" (lambda). That is why it is executed by using the standard Ruby `load` method. Renaming it will require changing the data structure. And at the same time, I'd like to avoid making breaking changes, so we'd need to keep the compatibility with `load`. But if you come up with some better names, feel free to share :)

**Comment by davidw** [comment]
How about...

* `lookup.call`
* `matcher.call`
* `connector.call`

I could also imagine something fancier like `set_target(target).from(source)` although I don't know how you'd get that working, not knowing the internals of all this!

**Comment by davidw** [comment]
Still interested.

**Comment by davidw** [comment]
Still interested
