### ISSUE TITLE
N+1 query problem with GraphQL (client side)

### ISSUE THREAD

**Issue by maurosbu** [exAspArk/batch-loader#54]
Hi,
I have two Rails application connected as follows:
APP1: expose data through GraphQL Api
APP2: define objects associated to APP1 data, it consume Api provided by APP1

Is there a way to avoid N+1 http requests problem (when loading APP1 data for a collection of APP2 objects)? 

I tried implementing something similar to what is presented at https://github.com/exAspArk/batch-loader#restful-api-example, it works (and performs caching) but it doesn't solve N+1 http requests problem.

BTW: I think that rating_lazy implementation is not correct, it should be

```ruby
class Post < ApplicationRecord
  def rating_lazy
    BatchLoader.for(id).batch do |ids, loader|
      Parallel.each(ids, in_threads: 10) { |id| loader.call(id, rating) }
    end
  end

   # ...
end
```

Many thanks,
Mauro

**Comment by exAspArk** [comment]
Hey @maurosbu,

BatchLoader doesn't automagically reduce the number of HTTP requests. Consider the following example:

```
Request A - 1 second
Request B - 1 second
Request C - 2 seconds
---------------------
Total duration - 4 seconds
```

With BatchLoader, it is possible to execute multiple HTTP requests concurrently with `Threads` or gems like `Parallel`, `Curb`, etc. Here are some [microbenchmarks](https://github.com/exAspArk/concurrent_http_requests) I ran a while ago. So the total execution time will be reduced (the requests started at the same instead of one after another) time but not the total number of requests.

```
Request A - 1 second
Request B - 1 second
Request C - 2 seconds
---------------------
Total duration - 2 seconds
```

However, if the HTTP API supports loading multiple objects with one request, then it is the best-case scenario for using BatchLoader to address N+1 HTTP requests. For example:

```
GET /api/users/1
GET /api/users/2
GET /api/users/3

vs

GET /api/users?ids=1,2,3
```

**Comment by maurosbu** [comment]
@exAspArk many thanks for your reply.

I've already tried the solution based on parallel gem, there are certainly advantages on execution time, but not on number of requests.

What about using GraphQL aliases? 
What do you thing about executing a query similar to the following one?

    query {
        user1: user(id: 1) {
            ...
        }
        user2: user(id: 2) {
            ...
        }
        user3: user(id: 3) {
            ...
        }
    }

One query to get them all (maybe few queries, if you set a limit on the number of items per query. 

The only problem I see is that queries must be assigned to constants and therefore cannot be created dynamically. Is this correct?

What do you think?

Many thanks.
Mauro

**Comment by maurosbu** [comment]
@exAspArk I enhanced the API so that it supports loading multiple objects with one request, and I'm trying to use BatchLoader to address N+1 HTTP requests. 

My application manage tasks. Each task is associated to owner, assignees, followers, .... Person is a remote entity that is managed in another application & exposed through a GraphQL API.

I would like to avoid N+1 HTTP request batch loading owner, assignees, followers.

```ruby
class Task < ApplicationRecord

  ...

  def owner
    BatchLoader.for(owner_id).batch do |owner_ids, loader|
      Sbx::Persons::Client.query(
        Sbx::Persons::Queries::PERSONS_QUERY, 
        variables: { 
          ids: owner_ids 
        }
      ).data.persons.each do |owner|
        loader.call(owner.id, owner)
      end
    end
  end

  def assignees
    ...
  end

  def followers
    ...
  end

  ...

end
```

I have a list of tasks that I wand to display on a page, if I loop the list and I print owner info then I still have the N+1 HTTP requests problem.

```ruby
tasks.each do |task|
  puts task.owner.name
end

# N HTTP requests executed
```

**_Touching_** the owner of each task let me avoid N HTTP request? 

```ruby
tasks.map(&:owner)   # touch owners
tasks.each do |task|
  puts task.owner.name
end

# 1 HTTP request executed
```

What am I missing?

Since I'm using GraphQL, is there a way to load all remote entities with just one request (even in case of heterogeneous entities)?

Many thanks,
Mauro

**Comment by maurosbu** [comment]
@exAspArk I'm sorry to bother you, do you know if it's a gem bug or if I'm using it improperly?

Many thanks in advance.
Mauro

**Comment by maurosbu** [comment]
Any update on this?
