### ISSUE TITLE
throwing undefined method `use' for BatchLoader::Middleware:Class

### ISSUE THREAD

**Issue by dehjli85** [exAspArk/batch-loader#64]
I added the batch-loader gem to a Ruby on Rails 5 project I'm working on, and realized that I was running into issues related to caching.  When I tried to disable caching between HTTP requests as suggested in the README documentation by adding the `use BatchLoader::Middleware` line into my graphql schema file I got this error:

`undefined method `use' for BatchLoader::Middleware:Class`

After some googling, I found this post:
https://medium.com/@bajena3/use-lazy-relationships-to-eliminate-n-1-queries-in-your-rails-apps-46ea2ce42162

which suggests configuring the middlware in the Rails `application.rb` file.  When I tried this, it worked for me.

So I guess my question: does the documentation needs to be updated, or am I doing something wrong following what's in the README?

**Comment by xgrei** [comment]
Can you make sure that the batch-loader gem is included in Gemfile.lock? 
you can show your Gemfile.lock content.

or 

you can try this following code in `application.rb`:

```
config.middleware.use BatchLoader::Middleware
```

**Comment by dehjli85** [comment]
batch-loader is in the Gemfile.lock
![image](https://user-images.githubusercontent.com/9154142/79498467-395bb480-7fde-11ea-881f-ff3f0a377eaf.png)

The code you suggested does work in the `application.rb` file, i'm just trying to understand why the code in the README documentation doesn't work for the benefit of others trying to use this gem

**Comment by exAspArk** [comment]
Hey @dehjli85,

Thank you for opening this issue. You're right there is a small inconsistency in the README.

* In https://github.com/exAspArk/batch-loader#restful-api-example:
```rb
config.middleware.use BatchLoader::Middleware
# ^ for rails projects
```

* In https://github.com/exAspArk/batch-loader#caching:
```rb
use BatchLoader::Middleware
# ^ for any rack-based projects such as Sinatra
```

---

We could change the later to something like:

```rb
use BatchLoader::Middleware

# For Rails projects, add the following line in config/application.rb
# config.middleware.use BatchLoader::Middleware
```

Feel free to contribute if you want :)
