### ISSUE TITLE
Using batch-loader to query a count of a has_many relation

### ISSUE THREAD

**Issue by reinvanimschoot** [exAspArk/batch-loader#65]
As the title says, I was wondering if it was possible to use batch-loader to query a has-Many relationship but specifically get a count of the amount items for a specific parent object.

I've taken a look at the closed issue but none of them really show a solution. There is one that touches this subject but more in the context of using values from one loader in another, which is not what I am trying to do per se.

**Comment by exAspArk** [comment]
Hey @reinvanimschoot. Do you mind sharing more context with some minimal code examples of what you're trying to do?
