### ISSUE TITLE
batch-loader not working for non-nullable graphql fields, returns "Cannot return null for non-nullable field"

### ISSUE THREAD

**Issue by bbugh** [exAspArk/batch-loader#68]
Hi! 👋 This is awesome, thank you so much for making it.

We're trying to add batch-loader for GraphQL and are running into an issue where we're getting a "cannot return null" on non-nullable fields.

```json
    {
      "message": "Cannot return null for non-nullable field Item.schedule"
    },
    {
      "message": "Cannot return null for non-nullable field Item.schedule"
    },
    {
      "message": "Cannot return null for non-nullable field Item.schedule"
    },
```

 If we make the field nullable, then it appears that BatchLoader is just not loading the association at all.

```json
          "schedule": null,
```

We added some logging to see the output, the code:

```ruby
  def batch_load_test(id, klass)
    BatchLoader::GraphQL.for(id).batch do |ids, loader|
      Rails.logger.error("*" * 80)
      Rails.logger.error("Batch Load #{klass}")
      Rails.logger.error("*" * 80)
      klass.where(id: ids).each { |record| loader.call(record.id, record) }
    end
  end

  def schedule
    batch_load_test(object.schedule_id, Schedule)
  end

  def location
    batch_load_test(object.zone_id, Location)
  end
```

In the log output, `Batch Load Location` appears correctly, but `Batch Load Schedule` doesn't.

I've tested a lot of variations and can't seem to find something that works consistently.

Thanks for reading!

---

graphql-ruby: 1.11.1
batch-loader: 1.5
ruby: 2.6.6

**Comment by bbugh** [comment]
This is still an issue

**Comment by joshuaclayton** [comment]
@bbugh I've also been running into this. I haven't tried to build a small reproducible test case and it's inconsistent in how it manifests. I *am* using `context.scoped_merge!` and seeing it crop up more with `has_many`-style relationships.

**Comment by jhirn** [comment]
Also getting an issue with this. For me the case seems to be when I have a non collection type that's a has-many underlying relationship.

**Comment by joshuaclayton** [comment]
@jhirn @bbugh one thing we'd possibly narrowed it down to – are you using the `cache: false` setting? Introducing that seemed to have helped, but again, with it being sporadic, it's hard to tell.

**Comment by jhirn** [comment]
Thanks @joshuaclayton. I'll give it a shot but sporadic is not my favorite flavor of coffee. 😆

**Comment by bbugh** [comment]
I'm not using cached and I still saw the issue with it on or off. Unfortunately since this causes a server error any chance of it happening is too much. 😢

**Comment by bbugh** [comment]
This is still an issue. 😔 We're blocked from using this effectively because we have so many places we would have to duplicate the Identical code.

**Comment by bbugh** [comment]
Damn, I can't reopen the issue either.

**Comment by bbugh** [comment]
@exAspArk would you mind reopening this so we can continue to track it?

**Comment by chintanparikh** [comment]
We've had this come up as well. We only noticed it once we added a `self.authorized?` method in our types so I assumed it was an authorization error. @bbugh are you also defining a `self.authorized?` method in your types? I'm also unable to reproduce it at all locally, only in production 🙃

**Comment by bbugh** [comment]
@chintanparikh not using any built-in graphql-ruby authorization, no. ☹️

**Comment by IngusSkaistkalns** [comment]
@bbugh i am not very familiar with `graphql-ruby` and also with `batch-loader`, but maybe you can resolve null cases using `default_value: []` option.

```ruby
    field :company_services, [Types::CompanyServiceType], null: false
    def company_services
      BatchLoader::GraphQL.for(object.id).batch(default_value: []) do |company_ids, loader|
        CompanyService.where(company_id: company_ids).each do |company_service|
          loader.call(company_service.company_id) { |collection| collection << company_service }
        end
      end
    end

    field :service_ids, [ID], null: false
    def service_ids
      BatchLoader::GraphQL.for(object.id).batch(default_value: []) do |_, loader|
        loader.call(object.id, company_services.sync.map(&:service_id))
      end
    end
```

This works for me, but I don't feel confident that "this is the way"
