### ISSUE TITLE
Warnings after updating to Ruby 2.7

### ISSUE THREAD

**Issue by sjovanelly** [exAspArk/batch-loader#69]
Using the batch loader is giving me some warnings now with 2.7.1.

rvm/gems/ruby-2.7.1/gems/batch-loader-1.5.0/lib/batch_loader/graphql.rb:58: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

Looks like this method needs a tweak...
    def batch(*args, &block)
      @batch_loader.batch(*args, &block)
      self
    end

More notes on potential fix.
https://bloggie.io/@kinopyo/how-to-fix-ruby-2-7-warning-using-the-last-argument-as-keyword-parameters-is-deprecated

**Comment by carrabi** [comment]
Any update on this? I'm experiencing the same issue as @sjovanelly

**Comment by dub-squared** [comment]
This should be resolved with the merge of #71
