### ISSUE TITLE
How I can filter associations values?

### ISSUE THREAD

**Issue by kalfaro** [exAspArk/batch-loader#70]
Example:
I have Users with a type attribute like reader and this users have Posts with a different states

I need to select only users with specific type attribute and the Post with a specific type... So basically filter the associations values

I hope the explanation was clear
Thanks for the help!

**Comment by tabuchid** [comment]
@kalfaro Did you figure out how to make this work?

**Comment by kalfaro** [comment]
@tabuchid Yes, I found a solution, but I'm not sure if is the best approach

I implement a 'Resolver' on child records and pass params from father using 'scoped_context', with this I can create custom queries depends of params

Please, let me know if exist others solutions for this
I appreciate the help!
Thanks
